---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ingest(ingest)
	classify_issue(classify_issue)
	resolve_order(resolve_order)
	prepare_action(prepare_action)
	draft_reply(draft_reply)
	admin_review(admin_review)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> ingest;
	admin_review --> draft_reply;
	classify_issue --> resolve_order;
	draft_reply -.-> __end__;
	draft_reply -.-> admin_review;
	draft_reply -.-> finalize;
	ingest -.-> classify_issue;
	ingest -.-> draft_reply;
	ingest -.-> resolve_order;
	prepare_action --> draft_reply;
	resolve_order --> prepare_action;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
